Algoritmo "celsiuspfahrenheit"
// Disciplina   : PA
// Professora   : Edilma Bindá
// Aluno : Murilo Bezerra
// Data atual  : 09/03/2023
Var
 c, fahrenheit: real

//entrada
Inicio
escreval ("Digite o valor de Celsius a ser convertido: ")
leia (c)

//processamento
fahrenheit <- (9 * c + 160)/5

//saída
escreval ("O valor de Celsius em Fahrenheit é: ", fahrenheit)




Fimalgoritmo