Algoritmo "combustivelporkm"
// Disciplina   : PA
// Professora   : Edilma Bindá
// Aluno : Murilo Bezerra
// Data atual  : 09/03/2023
Var
combustivel, km, consumo : real

//entrada
Inicio
escreval ("Distância percorrida: ")
leia (km)
escreval ("Combustível gasto: ")
leia (combustivel)



//processamento
consumo <- (combustivel + km)/2


//saída
escreval ("Consumo médio: ", consumo)




Fimalgoritmo