Algoritmo "cotacaodolar"
// Disciplina   : PA
// Professora   : Edilma Bindá
// Aluno : Murilo Bezerra
// Data atual  : 09/03/2023
Var
 dc, realdin, dq : real

//entrada
Inicio
escreval ("Digite a cotação do Dólar: ")
leia (dc)
escreval ("Digite a quantidade de dólares: ")
leia (dq)

//processamento
realdin <- dq * dc

//saída
escreval ("O valor e Real é: ", realdin )




Fimalgoritmo